# Numpy Arrays

## casting an array into numpy array

In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

## casting a list of list into numpy array

In [5]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## arange function of numpy
#### use shift + tab to get docstring

In [11]:
np.arange(0,10)
# just like range function of python 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
np.arange(0,7,2)

array([0, 2, 4, 6])

## zeros 

In [13]:
np.zeros(3)

array([0., 0., 0.])

### to see all attribute np.(hit 'tab')

In [15]:
np.zeros((5,5))
#  first no: number of rows
#  second no: number of columns

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## ones

In [16]:
np.ones(4)

array([1., 1., 1., 1.])

In [17]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## linespace

In [18]:
np.linspace(0,1,100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [28]:
np.linspace(1,7,6)

array([1. , 2.2, 3.4, 4.6, 5.8, 7. ])

In [31]:
np.linspace((-2,3),(2,5),4)
# use of tuple

array([[-2.        ,  3.        ],
       [-0.66666667,  3.66666667],
       [ 0.66666667,  4.33333333],
       [ 2.        ,  5.        ]])

## identity matrix(eye)

In [24]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Random

## rand

In [22]:
np.random.rand(5)
# it will create an array of the given shape you pass in and 
# it is going to populate it with random samples from uniform distribution from 0 to 1.

array([0.29752149, 0.38711485, 0.16648649, 0.02541394, 0.05885502])

In [23]:
np.random.rand(5,5)

array([[0.44052572, 0.30199243, 0.79647225, 0.28563505, 0.37636473],
       [0.51402148, 0.07207302, 0.50805045, 0.78847256, 0.86101078],
       [0.51737794, 0.05527207, 0.72440436, 0.14476657, 0.97948357],
       [0.44730964, 0.04460407, 0.0497367 , 0.89584186, 0.70933631],
       [0.60271435, 0.4325794 , 0.31780534, 0.79501338, 0.17330651]])

## randn

In [25]:
np.random.randn(2)
# this will return random numbers from standard normal distribution center around 0

array([1.10673778, 0.6970793 ])

In [35]:
np.random.randn(4,4)

array([[ 1.30930729,  0.88227693, -0.35960805,  1.06439857],
       [ 1.35875198,  0.28995614,  1.27869342,  0.47790997],
       [ 0.21515589,  0.27800708,  0.01932726,  0.15383526],
       [-0.54452423,  0.89888685,  0.87798988,  1.4885335 ]])

In [36]:
np.random.randint(1,100)
# low is inclusive
# high is exclusive

97

In [38]:
np.random.randint(1,100,10)

array([ 9, 77, 85, 71, 20, 83, 95, 87, 42,  7])

## reshape

In [39]:
arr = np.arange(0,25)

In [40]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [41]:
arr.reshape(5,5)
# total size remains same so check dimensions accordingly

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

## max , min , argmax,argmin


In [42]:
ranarr = np.random.randint(1,100,10)

In [43]:
ranarr

array([99, 80, 27, 38, 85, 82, 53, 33, 49, 43])

In [44]:
ranarr.max()

99

In [45]:
ranarr.min()

27

In [46]:
ranarr.argmax()

0

In [48]:
ranarr.argmin()

2

In [49]:
arr.shape

(25,)

## changing shape of arr

In [50]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [51]:
arr = arr.reshape(5,5)

In [52]:
arr.shape

(5, 5)

## dtype of an array

In [53]:
arr.dtype

dtype('int32')

In [54]:
from numpy.random import randint

In [55]:
randint(2,10)

4