## Numpy Indexing and Selection

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [8]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [9]:
arr[0:5] = 100

In [10]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

## assigning to slice of array to another array

In [11]:
arr = np.arange(0,11)

In [12]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
slice_of_arr = arr[0:6]

In [14]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [15]:
slice_of_arr[:] = 99

In [16]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [17]:
arr
# on calling the array arr back the modification in the elements
# i.e changing the elements to 99 in slice
# not only changes the slice_of_arr but it also changes or modifies the actual array

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## copy an array

In [18]:
arr_copy = arr.copy()

In [19]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [20]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [21]:
arr_copy[:] = 100

In [22]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [23]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

### if we actually grab the slice of an array and set it as variable without explicitly declaring that you want to copy the array we should keep in mind that  you are just viewing a link to original array and that changes you do will actually affect the original array 

In [24]:
slice_of_arr = arr[0:6].copy()

In [25]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [26]:
slice_of_arr[:] = 50

In [27]:
slice_of_arr

array([50, 50, 50, 50, 50, 50])

In [28]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## indexing of 2-D array

In [29]:
arr = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [30]:
arr

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [31]:
arr[0][0]

5

In [32]:
arr[0]

array([ 5, 10, 15])

In [33]:
arr[2,1]

40

In [34]:
arr[:2,1:]
# the rows will be of 0 and 1 index
# the columns will be of 1 and 2 index

array([[10, 15],
       [25, 30]])

In [35]:
arr[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [38]:
arr = np.arange(1,11)

In [41]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## comparison operations on arrays

In [45]:
arr>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

## conditional selection on arrays

In [42]:
bool_arr = arr>5

In [43]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [44]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [46]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [59]:
arr[arr<3]

array([0, 1, 2])

## revisiting reshape

In [58]:
arr_2d = np.arange(50).reshape(5,10)
# by default arange on one parameter will give value from 0 to 49

In [60]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [61]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [53]:
arr = np.arange(10)
# by default arange will make 1-D array

In [54]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
arr.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [56]:
arr.reshape(5,2,1)

array([[[0],
        [1]],

       [[2],
        [3]],

       [[4],
        [5]],

       [[6],
        [7]],

       [[8],
        [9]]])